<?php

declare(strict_types=1);

return [
    'http://docs.oasis-open.org/wsfed/authorization/200706' => [
        'AdditionalContext' => '\SimpleSAML\WebServices\Federation\XML\auth\AdditionalContext',
        'ClaimType' => '\SimpleSAML\WebServices\Federation\XML\auth\ClaimType',
    ],
    'http://docs.oasis-open.org/wsfed/federation/200706' => [
        'AdditionalContextProcessed' => '\SimpleSAML\WebServices\Federation\XML\fed\AdditionalContextProcessed',
        'ApplicationServiceEndpoint' => '\SimpleSAML\WebServices\Federation\XML\fed\ApplicationServiceEndpoint',
        'AttributeServiceEndpoint' => '\SimpleSAML\WebServices\Federation\XML\fed\AttributeServiceEndpoint',
        'AttributeServiceEndpoints' => '\SimpleSAML\WebServices\Federation\XML\fed\AttributeServiceEndpoints',
        'AuthenticationToken' => '\SimpleSAML\WebServices\Federation\XML\fed\AuthenticationToken',
        'AutomaticPseudonyms' => '\SimpleSAML\WebServices\Federation\XML\fed\AutomaticPseudonyms',
        'ClaimDialectsOffered' => '\SimpleSAML\WebServices\Federation\XML\fed\ClaimDialectsOffered',
        'ClaimTypesOffered' => '\SimpleSAML\WebServices\Federation\XML\fed\ClaimTypesOffered',
        'ClaimTypesRequested' => '\SimpleSAML\WebServices\Federation\XML\fed\ClaimTypesRequested',
        'ClientPseudonym' => '\SimpleSAML\WebServices\Federation\XML\fed\ClientPseudonym',
        'FederationID' => '\SimpleSAML\WebServices\Federation\XML\fed\FederationID',
        'FederationMetadata' => '\SimpleSAML\WebServices\Federation\XML\fed\FederationMetadata',
        'FederationMetadataHandler' => '\SimpleSAML\WebServices\Federation\XML\fed\FederationMetadataHandler',
        'FilterPseudonyms' => '\SimpleSAML\WebServices\Federation\XML\fed\FilterPseudonyms',
        'Freshness' => '\SimpleSAML\WebServices\Federation\XML\fed\Freshness',
        'IssuesSpecificPolicyFault' => '\SimpleSAML\WebServices\Federation\XML\fed\IssuesSpecificPolicyFault',
        'LogicalServiceNamesOffered' => '\SimpleSAML\WebServices\Federation\XML\fed\LogicalServiceNamesOffered',
        'PassiveRequestorEndpoint' => '\SimpleSAML\WebServices\Federation\XML\fed\PassiveRequestorEndpoint',
        'PassiveRequestorEndpoints' => '\SimpleSAML\WebServices\Federation\XML\fed\PassiveRequestorEndpoints',
        'ProofToken' => '\SimpleSAML\WebServices\Federation\XML\fed\ProofToken',
        'Pseudonym' => '\SimpleSAML\WebServices\Federation\XML\fed\Pseudonym',
        'PseudonymBasis' => '\SimpleSAML\WebServices\Federation\XML\fed\PseudonymBasis',
        'PseudonymServiceEndpoint' => '\SimpleSAML\WebServices\Federation\XML\fed\PseudonymServiceEndpoint',
        'PseudonymServiceEndpoints' => '\SimpleSAML\WebServices\Federation\XML\fed\PseudonymServiceEndpoints',
        'Realm' => '\SimpleSAML\WebServices\Federation\XML\fed\Realm',
        'ReferenceToken' => '\SimpleSAML\WebServices\Federation\XML\fed\ReferenceToken',
        'ReferenceToken11' => '\SimpleSAML\WebServices\Federation\XML\fed\ReferenceToken11',
        'RelativeTo' => '\SimpleSAML\WebServices\Federation\XML\fed\RelativeTo',
        'RequestProofToken' => '\SimpleSAML\WebServices\Federation\XML\fed\RequestProofToken',
        'RequestPseudonym' => '\SimpleSAML\WebServices\Federation\XML\fed\RequestPseudonym',
        'RequireBearerTokens' => '\SimpleSAML\WebServices\Federation\XML\fed\RequireBearerTokens',
        'RequireReferenceToken' => '\SimpleSAML\WebServices\Federation\XML\fed\RequireReferenceToken',
        'RequireSharedCookies' => '\SimpleSAML\WebServices\Federation\XML\fed\RequireSharedCookies',
        'RequireSignedTokens' => '\SimpleSAML\WebServices\Federation\XML\fed\RequireSignedTokens',
        'RequiresGenericClaimDialect' => '\SimpleSAML\WebServices\Federation\XML\fed\RequiresGenericClaimDialect',
        'SecurityToken' => '\SimpleSAML\WebServices\Federation\XML\fed\SecurityToken',
        'SecurityTokenServiceEndpoint' => '\SimpleSAML\WebServices\Federation\XML\fed\SecurityTokenServiceEndpoint',
        'SignOut' => '\SimpleSAML\WebServices\Federation\XML\fed\SignOut',
        'SingleSignOutNotificationEndpoint' => '\SimpleSAML\WebServices\Federation\XML\fed\SingleSignOutNotificationEndpoint',
        'SingleSignOutNotificationEndpoints' => '\SimpleSAML\WebServices\Federation\XML\fed\SingleSignOutNotificationEndpoints',
        'SingleSignOutSubscriptionEndpoint' => '\SimpleSAML\WebServices\Federation\XML\fed\SingleSignOutSubscriptionEndpoint',
        'SingleSignOutSubscriptionEndpoints' => '\SimpleSAML\WebServices\Federation\XML\fed\SingleSignOutSubscriptionEndpoints',
        'TargetScopes' => '\SimpleSAML\WebServices\Federation\XML\fed\TargetScopes',
        'TokenTypesOffered' => '\SimpleSAML\WebServices\Federation\XML\fed\TokenTypesOffered',
        'WebBinding' => '\SimpleSAML\WebServices\Federation\XML\fed\WebBinding',
    ],
];
